# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Inferior Planets
tagline:          'A journal.'
description:      'A quarterly jouranl by Beyza Ozer and Davis Land.'
url:              http://inferiorplanets.github.io
baseurl:          /

author:
  name:           'Davis Land & Beyza Ozer'
  url:            https://twitter.com/inferiorplanets

paginate:         5