# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            inferior planets
tagline:          'a journal.'
description:      'a journal.'
url:              http://inferiorplanets.com
baseurl:          /

author:
  name:           'Davis Land & Beyza Ozer'
  url:            https://twitter.com/inferiorplanets

paginate:         5