# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            inferior planets
tagline:          'a journal'
description:      'a journal'
url:              http://inferiorplanets.com
baseurl:          /
categories:       issue1
gems: 			  [jekyll-paginate]

author:
  name:           'Davis Land & Beyza Ozer'
  url:            https://twitter.com/inferiorplanets

paginate:         5
